name: Docker Image CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    CONTAINER: baybridge

jobs:
    docker-amd64:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v31
              with:
                  github_access_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Build image
              run: |
                  nix build .#docker
                  docker load < result
            - uses: actions/upload-artifact@v4
              with:
                  name: docker-image-amd64
                  path: result
    docker-arm64:
        runs-on: ubuntu-24.04-arm
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v31
              with:
                  github_access_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Build image
              run: |
                  nix build .#docker
                  docker load < result
            - uses: actions/upload-artifact@v4
              with:
                  name: docker-image-arm64
                  path: result
    docker-push:
        needs: [docker-amd64, docker-arm64]
        runs-on: ubuntu-latest
        services:
            registry:
                image: registry:2
                ports:
                    - 5000:5000
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/download-artifact@v5
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Tag & push docker image
              run: |
                  docker load < docker-image-amd64/result
                  docker tag $CONTAINER:latest localhost:5000/$CONTAINER:${GITHUB_REF#refs/*/}-${{ github.run_id }}-amd64
                  docker push localhost:5000/$CONTAINER:${GITHUB_REF#refs/*/}-${{ github.run_id }}-amd64

                  docker load < docker-image-arm64/result
                  docker tag $CONTAINER:latest localhost:5000/$CONTAINER:${GITHUB_REF#refs/*/}-${{ github.run_id }}-arm64
                  docker push localhost:5000/$CONTAINER:${GITHUB_REF#refs/*/}-${{ github.run_id }}-arm64

                  docker buildx imagetools create \
                    -t ghcr.io/nicolaschan/$CONTAINER:latest \
                    -t ghcr.io/nicolaschan/$CONTAINER:${GITHUB_REF#refs/*/}-${{ github.run_id }} \
                    localhost:5000/$CONTAINER:${GITHUB_REF#refs/*/}-${{ github.run_id }}-amd64 \
                    localhost:5000/$CONTAINER:${GITHUB_REF#refs/*/}-${{ github.run_id }}-arm64
